language: node_js
node_js:
- 7.7.3
deploy:
  api_key:
    secure: BRCuCWGThjRuToOHtrYGNfuQVG78kbwk+MeYknhI8Jssx8o9NKDWRMP1YE4f2lPW7XBY3H9TO+cRasaSt63ZygDgQd1i0dTeeCxmLt3Efh+Sj9mM3ivSrEbfevBorNZhyMqfRhDgQRKGeKWRXSk58/fFHFY/1MOlW20EU9xDlXZ4jRhVPV+peoWFmPynBl+YafA6Z/sp/w0tco0LnTgPxeJarCcP07ANSwMX82k4Hh63f/C3oIysUOis5hS9OK6L9ILcXOweEE/jjJ9Hngq53loGpJY6x1aRO9ZDKGmP/FCozXKM3dp6+xVYpWft26oO6sYniQ47s4bTYJz3f2L054qgtAlALcAMYA5XfZITpyFFvrH6MopY9njXGCE3t46k39/pe3zebfsu4T1N+JEhkzcp+9eTvYHViGGMVR9uQceLhzuRBBG9WBF7x63LQOjmBJ6i1i2rJa4LPlOz0YxJrZulDUR1EIHQjhpYP52bmnhzi+khkcXoldxKiHJ2gOHEXEwMzBodWc0uZWoObBhcwgnVKO54ijFvjqqQf0FO9boEEx5koUTBHmeM+AIr9zg6td2SYk4QCOidk9pVHUQpeDpjpSDLLUj3a/+DQWaebS3/M4hbUWJExJelaQFCRP74e8Kb1KFVhhCGI8cytPO6Fptgrc4eajjSH9/OOCe2MM4=
  email: vladimirmorulus@gamil.com
  provider: npm
  skip_cleanup: true
  before_script: npm run prepublish
  on:
    tags: true
    branch: master
